import LegalPage from "@/components/ui/LegalPage";

export const metadata = { title: "Çerez Politikası", description: "Auto Tokyo internet sitesi çerez ve tarayıcı depolama politikası." };
const heading = "text-xl font-bold text-white";

export default function Page() {
  return <LegalPage title="Çerez Politikası">
    <section><h2 className={heading}>Çerez ve Benzer Teknolojiler</h2><p className="mt-2">Çerezler tarayıcıya kaydedilen küçük verilerdir. Yerel depolama ve oturum depolaması benzer amaçlarla çalışan tarayıcı teknolojileridir. Bu site reklam, pazarlama veya ziyaretçi profilleme çerezi kullanmaz.</p></section>
    <section><h2 className={heading}>Kullanılan Teknolojiler</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[640px] border-collapse text-left text-xs"><thead><tr className="border-b border-white/20 text-white"><th className="p-3">Ad</th><th className="p-3">Tür</th><th className="p-3">Amaç</th><th className="p-3">Süre</th></tr></thead><tbody className="divide-y divide-white/10"><tr><td className="p-3">auto_tokyo_admin_session</td><td className="p-3">Zorunlu, birinci taraf çerez</td><td className="p-3">Yalnızca yönetici oturumunun güvenli biçimde sürdürülmesi</td><td className="p-3">En fazla 8 saat</td></tr><tr><td className="p-3">autoTokyoFavorites</td><td className="p-3">Yerel depolama</td><td className="p-3">Kullanıcının seçtiği favori araçları hatırlama</td><td className="p-3">Kullanıcı silene kadar</td></tr><tr><td className="p-3">autoTokyoComparison</td><td className="p-3">Yerel depolama</td><td className="p-3">Karşılaştırma listesini hatırlama</td><td className="p-3">Kullanıcı silene kadar</td></tr><tr><td className="p-3">autoTokyoRecentlyViewed</td><td className="p-3">Yerel depolama</td><td className="p-3">Son görüntülenen araçları cihazda gösterme</td><td className="p-3">Kullanıcı silene kadar</td></tr><tr><td className="p-3">Filtre ve açılış tercihleri</td><td className="p-3">Oturum depolaması</td><td className="p-3">Aynı tarayıcı oturumunda görünüm ve filtre tercihlerini koruma</td><td className="p-3">Tarayıcı oturumu sonuna kadar</td></tr></tbody></table></div></section>
    <section><h2 className={heading}>Hukuki Sebep ve Tercihler</h2><p className="mt-2">Yönetici oturum çerezi, açıkça talep edilen güvenli yönetim hizmetinin çalışması için kesinlikle gereklidir. Ziyaretçi tarafındaki yerel tercihler yalnızca kullanıcının favori, karşılaştırma veya filtre özelliğini aktif olarak kullanmasıyla kaydedilir ve sunucuya gönderilmez. Tarayıcı ayarlarından çerezleri ve site verilerini silebilir veya depolamayı engelleyebilirsiniz; bu durumda ilgili tercihler hatırlanmaz.</p></section>
    <section><h2 className={heading}>Politika Değişiklikleri</h2><p className="mt-2">Analitik, reklam veya pazarlama çerezi eklenmesi hâlinde bu politika güncellenir ve zorunlu olmayan teknolojiler çalıştırılmadan önce mevzuata uygun tercih/onay mekanizması sunulur. Ayrıntılı bilgi için KVKK’nın <a className="text-white underline" href="https://www.kvkk.gov.tr/Icerik/7353/Cerez-Uygulamalari-Hakkinda-Rehber" target="_blank" rel="noreferrer">Çerez Uygulamaları Hakkında Rehberini</a> inceleyebilirsiniz.</p></section>
  </LegalPage>;
}
