import Link from "next/link";
import { updateVehicleStatus } from "@/app/yonetim/actions";
import { query } from "@/lib/db";

export const dynamic = "force-dynamic";
const labels = { draft: "Taslak", published: "Yayında", sold: "Satıldı", archived: "Yayından Kaldırıldı" };
export default async function AdminVehiclesPage() {
  const vehicles = await query("SELECT id, brand, model, model_year, price, status FROM vehicles ORDER BY updated_at DESC");
  return <><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-tokyo-red">Portföy Yönetimi</p><h1 className="mt-3 font-display text-5xl font-bold uppercase text-white">Araçlar</h1></div><Link href="/yonetim/araclar/yeni" className="rounded-full bg-tokyo-red px-6 py-3 text-sm font-bold text-white">Yeni Araç Ekle</Link></div><div className="mt-8 overflow-hidden rounded-3xl border border-white/10"><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="bg-white/[.05] text-xs uppercase tracking-wider text-tokyo-muted"><tr><th className="p-5">Araç</th><th className="p-5">Yıl</th><th className="p-5">Fiyat</th><th className="p-5">Durum</th><th className="p-5">İşlemler</th></tr></thead><tbody className="divide-y divide-white/10">{vehicles.map((vehicle) => <tr key={vehicle.id} className="bg-tokyo-surface"><td className="p-5 font-semibold text-white">{vehicle.brand} {vehicle.model}</td><td className="p-5 text-tokyo-silver">{vehicle.model_year || "—"}</td><td className="p-5 text-tokyo-silver">{vehicle.price ? `${Number(vehicle.price).toLocaleString("tr-TR")} TL` : "—"}</td><td className="p-5"><span className="rounded-full bg-white/[.07] px-3 py-2 text-xs text-white">{labels[vehicle.status]}</span></td><td className="p-5"><div className="flex items-center gap-3"><Link href={`/yonetim/araclar/${vehicle.id}/duzenle`} className="rounded-xl border border-white/15 px-4 py-2 text-xs font-bold text-white">Düzenle</Link><form action={updateVehicleStatus} className="flex gap-2"><input type="hidden" name="vehicleId" value={vehicle.id} /><select name="status" defaultValue={vehicle.status} className="rounded-xl border border-white/10 bg-black px-3 py-2 text-xs text-white">{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="rounded-xl bg-tokyo-red px-4 py-2 text-xs font-bold text-white">Kaydet</button></form></div></td></tr>)}{!vehicles.length && <tr><td colSpan="5" className="p-10 text-center text-tokyo-muted">Veritabanında henüz araç bulunmuyor.</td></tr>}</tbody></table></div></div></>;
}
